### ISSUE TITLE
无法定位到正确的拼接位置

### ISSUE THREAD

**Issue by Robin-Rhee** [xiangwangfeng/M80ImageMerger#2]
你好 
我阅读了你的代码
算法棒棒哒
但是编译运行之后一直是提示拼接图片不同

于是设断点调试
发现两张图片在M80ImageMergeInfoGenerator类下面这个方法中
- (M80ImageMergeInfo *)infoByImage:(UIImage *)firstImage
                     secondImage:(UIImage *)secondImage

得到的x y length分别是

🎈-[M80ImageMergeInfoGenerator infoByImage:secondImage:] + 102📍 x = 2000

🎈-[M80ImageMergeInfoGenerator infoByImage:secondImage:] + 103📍 y = 2000

🎈-[M80ImageMergeInfoGenerator infoByImage:secondImage:] + 104📍 length = 273

也就是说在QQ上截图可识别的相同部分只是输入框以下的部分
我用MD5代替CRC32实验之后也是如此
说明和哈希算法无关
而且我的截图中没有GIF
我的image.size = NSSize: {1125, 2001}
哈哈 希望能得到你的回复

**Comment by xiangwangfeng** [comment]
这个最好有具体的图片让我检查下

**Comment by Robin-Rhee** [comment]
已发到你的GMAIL ^_^

**Comment by xiangwangfeng** [comment]
我看了大致原因应该是这样的:因为聊天的背景并不是一个纯色背景，这样导致一个问题是滑动后虽然肉眼看起来是差不多的，但是在机器看来，每一行的像素信息已近完全不一样了....
现在的算法完全没法处理这种情况.....得用更加复杂的方法 （有空想想，哈哈）

**Comment by Robin-Rhee** [comment]
请问这儿的纯色如何理解？
另外能否拓展说说机器如何识别像素点？
^_^

**Comment by xiangwangfeng** [comment]
机器看像素点就是RGB
如果是纯色背景，无论聊天记录如何移动，它和背景组合成的行数据是一致的
但是如果自定义聊天界面背景，那么移动后聊天内容合背景组成的数据和在旧的位置上就不一致了
至于复杂的识别就属于计算机视觉的范畴了，这方面我基本就不懂了。
