### ISSUE TITLE
应该是CTAssetsPickerController的问题吧？

### ISSUE THREAD

**Issue by LhiKien** [xiangwangfeng/M80ImageMerger#5]
编译时提示：
Class PLBuildVersion is implemented in both AssetsLibraryServices and PhotoLibraryServices. One of the two will be used. Which one is undefined.
按道理，AssetsLibrary和PhotoLibrary用一个就能解决问题了吧？
AssetsLibrary算不算是过时了，用Photos库是不是会好一些？

**Comment by LhiKien** [comment]
另外，为什么不把 CTAssetsPickerController 放到 Podfiles 里面呢？

**Comment by xiangwangfeng** [comment]
CTAssetsPickerController 的作者已经不维护了，最新的一个 podspec 在 1.0.0  cocoapods 下有 bug，无法正确引入资源文件
