### ISSUE TITLE
不感觉有用

### ISSUE THREAD

**Issue by mozzie2015** [xiangwangfeng/M80ImageMerger#6]
试了很多图片，demo中的一次都没有成功过，不知是方法不对还是我的操作很奇葩

**Comment by xiangwangfeng** [comment]
操作可以推荐看这个视频 https://nos.netease.com/nim/MTAxMTAwMg==/bmltYV8xMTAwOV8xNDk1Nzg4MTEwNjgzXzJiMTAzZDE0LWRlNzgtNDMwMi05OTBjLTM3NzY2ODJlYTQyMw==

现在的算法是有限制的，具体参考 readme 的说明
